attributes:
  ceph_hammer_ec_rgw:
    value: true
    label: 'Use erasure pool for RGW'
    description: 'Description for text field'
    weight: 25
    type: "checkbox"
  ceph_hammer_repl_count:
    value: 2
    label: 'Ceph replication count'
    description: 'Description for text field'
    weight: 30
    type: "text"

description: "Ceph plugin configuration"
