#!/bin/bash

set -eux

ROOT="$(dirname `readlink -f $0`)"
MODULES="${ROOT}"/deployment_scripts/puppet/modules
TMP_DIR="${ROOT}"/tmp
mkdir -p "${MODULES}"
mkdir -p "${TMP_DIR}"
REPO_PATH='https://github.com/stackforge/fuel-library/tarball/f43d885914d74fbd062096763222f350f47480e1'

wget -qO- "${REPO_PATH}" | \
    tar -C "${MODULES}" --strip-components=3 -zxvf - \
    stackforge-fuel-library-f43d885/deployment/puppet/{inifile,stdlib}

RPM_REPO="${ROOT}"/repositories/centos/
RPM_REPO_URL="http://mirror.fuel-infra.org/fwm/6.0/centos/os/x86_64/Packages/"
RPM_PACKAGES=""

DEB_REPO="${ROOT}"/repositories/ubuntu/
DEB_REPO_URL="http://ceph.com/debian-hammer/pool/main/c/ceph/"
DEB_PACKAGES="ceph-common_0.94.2-1trusty_amd64.deb
ceph-deploy_1.5.26trusty_all.deb
ceph-fs-common_0.94.2-1trusty_amd64.deb
ceph-mds_0.94.2-1trusty_amd64.deb
ceph-resource-agents_0.94.2-1trusty_amd64.deb
ceph_0.94.2-1trusty_amd64.deb
librados2_0.94.2-1trusty_amd64.deb
librbd1_0.94.2-1trusty_amd64.deb
python-ceph_0.94.2-1trusty_amd64.deb
python-rados_0.94.2-1trusty_amd64.deb
radosgw-agent_1.2.3trusty_all.deb
radosgw_0.94.2-1trusty_amd64.deb"


download_packages () {
    local REPO_PATH=$1
    local REPO_URL=$2
    local PACKAGES=$3

    for PACKAGE in ${PACKAGES}; do
        wget -P ${REPO_PATH} -nc ${REPO_URL}${PACKAGE}
    done
}

#Currently only Ubuntu is supported.
#download_packages ${RPM_REPO} ${RPM_REPO_URL} "$RPM_PACKAGES"
download_packages ${DEB_REPO} ${DEB_REPO_URL} "$DEB_PACKAGES"
